services:
  mysql:
    build: ./mysql
    image: mysql:8.0
    container_name: mysql
    restart: always
    mem_reservation: 128m
    mem_limit: 256m
    cpus: "0.5"
    cpu_shares: 1024
    networks:
      - docker_net
      - voip_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mysql.rule=Host(`db.ss2b.com.br`)"
      - "traefik.http.routers.mysql.tls=true"
      - "traefik.http.routers.mysql.tls.certresolver=lets-encrypt"
      - "traefik.http.services.mysql.loadbalancer.server.port=3101"
      - "traefik.docker.network=docker_net"
    ports:
      - "3301:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "America/Sao_Paulo"
    volumes:
      - mysql_data:/var/lib/mysql
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
networks:
  docker_net:
    driver: bridge
    external: true
  voip_net:
    driver: bridge
volumes:
  mysql_data:
    name: mysql_data
    driver: local
